name: Code Analysis
on:
    push:
        branches: [ '**' ]
    pull_request:
jobs:
    lint-frontend:
        name: Lint Frontend
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: '18'

            -   name: Install dependencies
                run: npm install

            -   name: Run ESLint
                run: npm run lint

    lint-backend:
        name: Lint Backend
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: '18'

            -   name: Install dependencies
                run: npm install

            -   name: Run ESLint
                run: npm run lint
